version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - model-data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FASTTEXT_MODEL_PATH=/app/data/cc.fr.300.reduced.vec

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  model-data: